# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Build settings
markdown: kramdown
permalink: none
post_dirs: false
kramdown:
    parse_block_html: true

# Multi Language
gems: ['jekyll-paginate']

exclude: ['build.sh', '*.zip', '*.img', '*.iso']

